version: '3'
services:
  terraform:
    build:
      context: ./docker
      dockerfile: docker/Dockerfile
    volumes:
      - ./helm:/project/helm
      - ./bin:/project/bin
      - ~/.kube:/root/.kube
      - ./bin/.bashrc:/root/.bashrc
    entrypoint:
      /bin/bash
